### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghandeb** [odtu/motor-design#4]
plunger (C:/Users/User/Desktop/)
  Maxwell2DDesign1 (Magnetostatic, XY)
    [error] Unable to locate or start COM engine on 'Local Machine' : unable to create engine process (12:58:47 AM  Nov 24, 2017)

şu şekilde bir hata alıyorum, programın firewallu geçmesi için izinleri düzenledim, sonra hem windowsun hem de antivirüs yazılımının firewallunu kapattım ama olmadı, google'a yazınca da pek faydalı bir şey çıkmadı, ne yapmam gerekiyor bilemedim

**Comment by ozank** [comment]
valla benim de bir fikrim yok. @rezazeinali ?

**Comment by ghandeb** [comment]
çözümünü bulamayınca silip yeniden yükledim 😕
