### ISSUE TITLE
magnetization - week4

### ISSUE THREAD

**Issue by hakansrc** [odtu/motor-design#5]
Magnetization orientation ı ve north south poleları nasıl assign ediyoruz? material property lerden yürümeyi denedik ama nedense istediğimiz gibi flux vektörleri elde edemiyoruz.

**Comment by MutluKaan** [comment]
Mıknatıs özelliği olan bir malzeme seçip "view/edit material" sekmesine gidince burada orientation çıkıyor. Aynı sayfanın sağ üst kısmında koordinat sistemini de değiştirebiliyorum. Initial position için y ekseninde magnetization olan bir mıknatıs ile başladım, flux vektörleri düzgün oldu. (N S pole lar için ayrı ayrı hacimler oluşturmadım). Yine "view/edit material" sekmesinde alt tarafta OK tuşunun hemen üzerindeki drop down listten de magnetin özelliklerini seçebildim (bunu bulmak için de zaman harcadığım için yazmak istedim umarım faydası dokunur).

**Comment by hakansrc** [comment]
teşekkür ederim hocam

**Comment by ozank** [comment]
:clap: :clap:
