### ISSUE TITLE
Week 5 - Winding Design

### ISSUE THREAD

**Issue by ilkersahin78** [odtu/motor-design#6]
_"There are no stupid questions.
Even if there is, asking a stupid question doesn’t mean that you are stupid."_

Sığır olmadığıma hemfikirsek bağzı sorularım olacak. Evvelki hafta anlatıldıysa affola:

1- Length bilmek gerekmiyor mu?
2- Winding muallakta mı duracak? Bunun slot u yok mu? Müsait alanın yarısı tooth yarısı slot mu alalım?
3- Bu minnak motor şebekeye bağlanılası bişey değil (24V). Bakmam ki harmoniğine, concentrated çakar geçerim?
4- Madem inverter driven, pole sayısına nasıl karar verebilirim ki şu durumda, 2 pole der geçerim basit olsun diye
5-Current density  4 A/mm2 de motorun gücünü bilmemiz lazım, kaç amper çekicek bu?

**Comment by MutluKaan** [comment]
Kendi bakış açımdan cevap atmış olayım, yazdıklarım teyide muhtaçtır:

1- Length geçen haftadan dolayı 0.1 m alıyorum.
2- Aircored machine olacak bizimkisi, dolayısıyla slotlar yok.
3- 24V'u oluşturmak için winding factöre biz karar vereceğiz gibi anladım ben. (Daha o kısma gelmedim ama 1500 RPM'deki back-emf kendiliğinden 24V'a denk gelmeyebilir)
4- Magnet tarafı (yine geçen haftaya bağlı olarak) 2 pole olarak alıyorum.
5- Winding kaç mm2 olabiliyorsa motorun rated akımı da en fazla ona bağlı olarak hesaplanıp devam edilecek gibi anladım. Gerilimi de belli olduğu için oradan rated power hesaplayacağız sanırım.

**Comment by ozank** [comment]
Selamlar,
1- Evet uzunluğu 10 cm alabilirsiniz, ama bi de end winding uzunluğunu hesaplamanız gerekecek.
2- Evet air-cored olduğu için slot yok, fikir vermesi açısından şöyle bişey olacak (ama açılı filan kabul etmiyoz henüz, düz kabul edin)
https://www.maxonmotor.com/medias/sys_master/root/8811452170270/ACTUATOS-IN-AEROSPACE-PIC4-GALLERY.jpg
3-Evet sinüs dalgada full-pitch yapmak en mantıklısı olabilir. Ama derste bi de trapezoidal B dağılımı üstünden geçeriz, onda short-pitch yapılabilir.  Ama her türlü distributed winding olacak, tüm çapı kaplamak için.
4- 2 pole olacak 
5- Biraz tersten gidecez, 4 A/mm2 olursa, gücü kaç çıkacak ona bakmak istiyoruz. Kablo dirençlerini düşüp, verim ve anma gücü bulunabilir.
